version: "3"
services:

  rise:
    image: jpopesculian/rise-node:arm-latest
    depends_on:
      - redis
      - postgres
    ports:
      - "127.0.0.1:5555:5555"
    networks:
      - overlay
    environment:
      NETWORK: mainnet
    restart: on-failure

  redis:
    image: arm32v6/redis:5-alpine
    networks:
      - overlay
    restart: on-failure

  postgres:
    image: jpopesculian/rise-node_postgres:arm-mainnet-latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: rise
      POSTGRES_DB: rise_db
    networks:
      - overlay
    restart: on-failure

volumes:
  postgres-data:

networks:
  overlay:
