version: "3"
services:

  rise:
    build: .
    depends_on:
      - redis
      - postgres
    ports:
      - "127.0.0.1:5555:5555"
    networks:
      - overlay
    restart: on-failure

  redis:
    image: redis:5-alpine
    networks:
      - overlay
    restart: on-failure

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: rise
      POSTGRES_DB: rise_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - overlay
    restart: on-failure

volumes:
  postgres-data:

networks:
  overlay:
